// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteHelpdesk.Data;

#nullable disable

namespace SiteHelpdesk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230208000946_UpdateChamadosModel")]
    partial class UpdateChamadosModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteHelpdesk.Models.ChamadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aplicativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppVersao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChamadoData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChamadoHora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int?>("IdCard")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvHora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OvStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Reproduzido")
                        .HasColumnType("bit");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select2Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPai")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdPai");

                    b.ToTable("Select2");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select3Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPai")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdPai");

                    b.ToTable("Select3");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select4Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPai")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdPai");

                    b.ToTable("Select4");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.SelectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Select");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select2Model", b =>
                {
                    b.HasOne("SiteHelpdesk.SelectModels.SelectModel", "Select")
                        .WithMany()
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Select");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select3Model", b =>
                {
                    b.HasOne("SiteHelpdesk.SelectModels.Select2Model", "Select")
                        .WithMany()
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Select");
                });

            modelBuilder.Entity("SiteHelpdesk.SelectModels.Select4Model", b =>
                {
                    b.HasOne("SiteHelpdesk.SelectModels.Select3Model", "Select")
                        .WithMany()
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Select");
                });
#pragma warning restore 612, 618
        }
    }
}
